intf_libs = # Interface dependencies.
#import intf_libs += libstd-modules%lib{std-modules}
impl_libs = # Implementation dependencies.
#import impl_libs += libhello%lib{hello}

lib{mcis17a}: {cxx mxx}{**} $impl_libs $intf_libs

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

# Export options.
#
lib{mcis17a}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{mcis17a}: bin.lib.version = @"-$version.project_id"
else
  lib{mcis17a}: bin.lib.version = @"-$version.major.$version.minor"

# Install into the libmcis17a/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{mxx}{*}:
{
  install         = include/libmcis17a/
  install.subdirs = true
}
